- poetry.lock
- pyproject.toml
Loosening python requirements from `>=py3.6.10` -> `>=3.6.0`, which should also be supported.
Still passes tests on 3.6.0 based on testing locally, and it gives more flexibility for use in other projects.
> Loosen lowerbound python requirements

- fgpyo/util/inspect.py
- fgpyo/util/tests/test_metric.py
- fgpyo/util/types.py
Following bugfixes:
- Optional parsing was running into issues because the NoneType had no parser, which was leading to Exceptions that were being hidden by error handling. This resolves that issue
- several imports were running into issues because the functions didn't exist as named or were private. This was also being caught by error handling and therefore not causing CI issues. This resolves that issue.
- Parsing was using `partial.func`, rather than directly calling the partial, which was leading to errors that were, again, being caught by error handling. This resolves that issue.
Features:
- adds an `is_optional` function to check if a type is optional
- supports optional parsing more robustly
Also adds tests for these problems
> [bugfix] Fixes issue with Optional parsing for Metric class

- fgpyo/util/inspect.py
- fgpyo/util/metric.py
- fgpyo/util/tests/test_metric.py
In branch `issue_10` lines were changed in `Metric.format.py()` so that empty lists are formatted as `""` and other lists do not include `[]`. Lines were also changed in `inspect.py/get_parser()` so that an empty string can be parsed as a list.
> Remove square brackets when writing lists to disk

- fgpyo/fasta/builder.py
- fgpyo/sam/tests/test_clipping.py
- fgpyo/util/inspect.py
- fgpyo/util/metric.py
- fgpyo/util/tests/test_inspect.py
- fgpyo/util/tests/test_metric.py
This is a breaking change, since previously it would default to an Assertion Error.
I also fixed a few docstring issues.
> Metric.read should support skipping extra columns

- fgpyo/util/metric.py
- fgpyo/util/tests/test_metric.py
Closes https://github.com/fulcrumgenomics/fgpyo/issues/51
> feat: offer GZIP support for Metric IO

- fgpyo/vcf/__init__.py
- fgpyo/vcf/builder.py
- fgpyo/vcf/tests/test_builder.py
* Based on pysam
* Adds helper reader and writer utilties
* * reader blocks stderr messages for index older than vcf
* Adds PysamVariantBuilder builder class for relatively easy construction of variants
* * builder has utilty methods for adding necessary headers
> Add vcf module

- fgpyo/sam/__init__.py
- fgpyo/sam/builder.py
- fgpyo/sam/tests/test_builder.py
- poetry.lock
- pyproject.toml
The support for ``TemplateCoordinate`` sorted records is coming in the first wave of wrapped `pysam` `samtools` dispatch calls.
This should address https://github.com/fulcrumgenomics/fgpyo/issues/20.
This is also more or less identical to an addition made to samwell in a PR merged presumably after the sambuilder module code was pulled over from samwell to here.
> Adding the option to specify the sort order of an output SAM file produced by SamBuilder.

- fgpyo/io/tests/test_io.py
- fgpyo/util/inspect.py
- fgpyo/util/logging.py
- fgpyo/util/metric.py
- fgpyo/util/types.py
- fgpyo/vcf/tests/test_builder.py
- poetry.lock
- pyproject.toml
* Move to current latest version of pytest to avoid deprecation warning
* Move to current latest version of mypy
* Correct multiple problems with type and import flagged by newer mypy
Closes #73
> Fix type problems found by latest mypy

- docs/api.rst
- fgpyo/fasta/builder.py
- fgpyo/io/__init__.py
- fgpyo/read_structure.py
- fgpyo/sam/builder.py
- fgpyo/sam/clipping.py
- fgpyo/util/inspect.py
- fgpyo/util/metric.py
- fgpyo/vcf/__init__.py
Closes #72 
Also fixes up all these warnings:
```console
fgpyo/sam/builder.py:docstring of fgpyo.sam.builder.SamBuilder.add_pair:8: WARNING: Unexpected indentation.
fgpyo/sam/builder.py:docstring of fgpyo.sam.builder.SamBuilder.add_pair:9: WARNING: Bullet list ends without a blank line; unexpected unindent.
fgpyo/sam/builder.py:docstring of fgpyo.sam.builder.SamBuilder.add_pair:15: WARNING: Unexpected indentation.
fgpyo/sam/clipping.py:docstring of fgpyo.sam.clipping.ClippingInfo.query_bases_clipped:1: WARNING: duplicate object description of fgpyo.sam.clipping.ClippingInfo.query_bases_clipped, other instance in api, use :noindex: for one of them
fgpyo/sam/clipping.py:docstring of fgpyo.sam.clipping.ClippingInfo.ref_bases_clipped:1: WARNING: duplicate object description of …
```
> Add VCF module to docs and fixup docs warnings

- docs/api.rst
- fgpyo/fastx/__init__.py
- fgpyo/fastx/tests/test_fastx_zipped.py
Helpful addition? Docs appear to render correctly on my local machine:
> Add a context manager for zipping FASTX files

- fgpyo/fastx/__init__.py
- fgpyo/fastx/tests/test_fastx_zipped.py
- fgpyo/read_structure.py
isort insisted on fixing these when I ran `ci/check.sh`  - afaict I'm using the version specified in the lock file, 5.10.1
> chore: isort

- fgpyo/sam/__init__.py
- fgpyo/sam/tests/test_supplementary_alignments.py
I thought it'd be helpful to abstract away the logic for validating the presence of an SA tag and type-checking, since that's going to be necessary most of the time `parse_sa_tag` is used in practice
> feat: add SupplementaryAlignment constructor from read

- fgpyo/util/inspect.py
- fgpyo/util/tests/test_inspect.py
`type(type(None))` returns `<class type>`, and so `isinstance(type_, type(type(None)))` always returns `True`. Instead, we want `type_ is type(None)`. I used @msto suggestion to alias `NoneType = type(None)` to avoid the flake8 E721 error.
Closes #94.
> Fix the check for `None` type in `inspect._get_parser`

- fgpyo/util/inspect.py
- fgpyo/util/tests/test_inspect.py
Created public functions for the four built-in collection types handled by `_get_parser`: list, set, tuple, and dict.
Closes #100
> Factor out functions for parsers for built-in collections

- fgpyo/sam/__init__.py
- fgpyo/sam/tests/test_supplementary_alignments.py
I have a context where it'd be helpful if the `end` were readily accessible.
> feat: Add end property on SupplementaryAlignment

- fgpyo/util/metric.py
this can be typed more specifically than `Any`
> fix: Add return type hint to Metric.read()

- fgpyo/util/inspect.py
This PR includes two minor QoL fixes
- I found the aliased import of `DataclassInstance` to `DataclassesProtocol` unnecessary, especially since it conflicted with the naming convention of `AttrInstance`
- I updated the `*Instance` definitions to reflect the canonical definitions for each. (In particular, the implementation for `AttrInstance` was bugged since `__attrs_attrs__` can be a tuple of attributes, not a dict)
> fix: DataclassInstance and AttrInstance protocols

- fgpyo/io/__init__.py
- fgpyo/io/tests/test_io.py
Fixing typos.
I've renamed `assert_file_is_writeable` to `assert_file_is_writable`, and added an alias under the former name that raises a `DeprecationWarning`.
> refactor: writeable -> writable

- fgpyo/io/__init__.py
- fgpyo/io/tests/test_io.py
Closes #117 
- I updated `assert_path_is_readable()` and `assert_path_is_writable()` to specially handle `/dev/stdin` and `/dev/stdout`, respectively
- I updated `assert_path_is_readable()` to specifically require that the input `path` is a file, not just that it is not a directory. (This disparity between the two functions is why `stdin` was ok for the `readable` check, but `stdout` was not for the `writable` check)
- I lightly refactored the chain of assertions in `assert_path_is_writable()` to produce more specific error messages and for legibility.
- I updated `assert_path_is_writable()` so the absolute path is considered regardless of the value of `parent_must_exist`
- Minor housekeeping in the corresponding unit tests
> fix: r/w assertions

- fgpyo/util/metric.py
- fgpyo/util/tests/test_metric.py
I'd like to add a function to convert a `Metric` instance to a dict. (In support of #107 )
I'm currently receiving the following mypy errors, which I suspect are due to a bug in how `Metric` is typed - as mypy appears to be inferring that `Metric` is a union of `DataclassInstance` and `type[DataclassInstance]`, when it should only be the former.
```
fgpyo/util/metric.py:346: error: Argument 1 to "asdict" has incompatible type "DataclassInstance | type[DataclassInstance]"; expected "DataclassInstance"  [arg-type]
fgpyo/util/metric.py:347: error: Argument 1 to "has" has incompatible type "Metric[Any]"; expected "type"  [arg-type]
fgpyo/util/metric.py:348: error: Argument 1 to "asdict" has incompatible type "type[AttrsInstance]"; expected "AttrsInstance"  [arg-type]
fgpyo/util/metric.py:348: …
```
> feat: Add asdict()

- fgpyo/util/metric.py
- fgpyo/util/tests/test_metric.py
@nh13 @tfenne @clintval 
I'm breaking up #107 into a few smaller PRs.
This one introduces the `read_header()` function, which I've implemented as a static method on `Metric`.
This may look familiar, and I apologize for the duplication - similar functionality has shown up in both #107 and #103. I've incorporated the feedback left on both PRs, and would like to consolidate on this PR (with the others to be based off this one). 
The purpose of the `read_header()` function is two-fold: 1) to support the incoming `MetricWriter` class, and 2) to generalize `Metric.read` to support files with lines preceding the header (e.g. Picard metric files).
I'm introducing a dataclass to contain both the detected fieldnames and any preceding lines, so if we choose we can write metric files with the same …
> feat: Add `read_header()`

- fgpyo/io/__init__.py
The return type of `to_reader` and `to_writer` can (and should?) be narrowed to `io.TextIOWrapper`
https://github.com/fulcrumgenomics/fgpyo/pull/103#discussion_r1539758711
> refactor: Narrow typing on `to_reader` and `to_writer`

- fgpyo/sam/__init__.py
Addressing https://github.com/fulcrumgenomics/fgpyo/issues/67
@nh13 @tfenne would you entertain something like this?
Two open questions 
- whether writing to `stdout` should default to SAM or BAM
- I'm not sure how best to test these. In the past when unit testing against `sys.stdin` I've used `pytest.MonkeyPatch` and a `StringIO`, but `pysam` doesn't support reading from `StringIO`
> feat: Support stdin/stdout special cases in sam.reader/writer

- fgpyo/sam/__init__.py
- fgpyo/util/inspect.py
- fgpyo/util/types.py
https://docs.astral.sh/ruff/rules/raise-without-from-inside-except/
> What it does
> Checks for raise statements in exception handlers that lack a from clause.
> 
> Why is this bad?
> In Python, raise can be used with or without an exception from which the current exception is derived. This is known as exception chaining. When printing the stack trace, chained exceptions are displayed in such a way so as make it easier to trace the exception back to its root cause.
> 
> When raising an exception from within an except clause, always include a from clause to facilitate exception chaining. If the exception is not chained, it will be difficult to trace the exception back to its root cause.
> chore: fix B904 violations

- fgpyo/fasta/tests/test_builder.py
- fgpyo/sam/tests/test_supplementary_alignments.py
- fgpyo/tests/test_read_structure.py
https://docs.astral.sh/ruff/rules/assert-raises-exception/
> ### What it does
> 
> Checks for `assertRaises` and `pytest.raises` context managers that catch `Exception` or `BaseException`.
> 
> ### Why is this bad?
> 
> These forms catch every `Exception`, which can lead to tests passing even if, e.g., the code under consideration raises a `SyntaxError` or `IndentationError`.
> 
> Either assert for a more specific exception (builtin or custom), or use `assertRaisesRegex` or `pytest.raises(..., match=<REGEX>)` respectively.
> chore: fix B017 violations

- fgpyo/util/tests/test_logging.py
https://docs.astral.sh/ruff/rules/unused-loop-control-variable/
> ### What it does
> 
> Checks for unused variables in loops (e.g., for and while statements).
>
> ### Why is this bad?
> 
> Defining a variable in a loop statement that is never used can confuse readers.
> 
> If the variable is intended to be unused (e.g., to facilitate destructuring of a tuple or other object), prefix it with an underscore to indicate the intent. Otherwise, remove the variable entirely.
> chore: fix B007 violations

- fgpyo/io/__init__.py
https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/
> ### What it does
> 
> Checks for `warnings.warn` calls without an explicit `stacklevel` keyword argument.
>
> ### Why is this bad?
> 
> The `warnings.warn` method uses a `stacklevel` of 1 by default, which limits the rendered stack trace to that of the line on which the warn method is called.
> 
> It's recommended to use a `stacklevel` of 2 or higher, give the caller more context about the warning.
> chore: fix B028 violations

- fgpyo/util/inspect.py
https://docs.astral.sh/ruff/rules/set-attr-with-constant/
> What it does
> Checks for uses of setattr that take a constant attribute value as an argument (e.g., setattr(obj, "foo", 42)).
> 
> Why is this bad?
> setattr is used to set attributes dynamically. If the attribute is defined as a constant, it is no safer than a typical property access. When possible, prefer property access over setattr calls, as the former is more concise and idiomatic.
> chore: fix B010 violations

- fgpyo/sequence.py
- fgpyo/tests/test_sequence.py
Add method to calculate the length of the longest homopolymer in a string of bases. Corresponding unit tests also added.
> Feat: add longest_hp_len() to fgpyo/sequence.py

- fgpyo/fasta/sequence_dictionary.py
- poetry.lock
- pyproject.toml
- tests/fgpyo/fasta/test_sequence_dictionary.py
> feat: adds classes and methods for sequence dictionaries

- README.md
This documentation is intended to clarify a couple points of confusion I encountered when adding #163 
1. `mkdocs` and its dependencies are declared as extras rather than as a dependency group - I'm sufficiently novice to `poetry` that I didn't know how to install these, and I thought including the required flag in the README would be helpful for other folks coming in who want to contribute.
2. Since `ci/check.sh` runs `mkdocs`, these dependencies aren't _really_ optional, and so our installation instructions should include them by default.
I opened #165 to discuss possibly reorganizing, but I'd like to get this PR in as-is so the docs are up-to-date.
> doc: Add installation of `mkdocs` dependencies to README

- fgpyo/util/metric.py
Reverts fulcrumgenomics/fgpyo#110
Closes #172
> Revert "fix: Add return type hint to Metric.read()"

- fgpyo/platform/illumina.py
- tests/fgpyo/platform/test_illumina.py
Adds an `__init__.py` in `fgpyo/platform/` and ensures docstrings play nice with RTD.
> fix:  RTD needs an  `__init__.py` in `fgpyo/platform/`

- fgpyo/fasta/sequence_dictionary.py
Was getting:
ModuleNotFoundError: No module named 'strenum'
> fix: fgpyo.fasta.sequence_dictionary incorrect StrEnum import

- .github/workflows/pythonpackage.yml
We are now using a organizational-level token
> ci: remove the use of github-actions-ci environment

- fgpyo/sequence.py
- tests/fgpyo/test_sequence.py
The `longest_dinucleotide_run_length` method is optimized for dinucleotides, whereas the `longest_multinucleotide_run_length` method is general for any repeat of length N.
> feat: add methods for computing run lengths of repeats in a sequence

- fgpyo/util/metric.py
- fgpyo/util/tests/test_metric.py
I split the remaining code in #107 into two PRs to facilitate review.
This PR introduces several of the assertion methods used when constructing the `MetricWriter`. (See #107 for how they are used in practice).
> feat: Add assertions to support `MetricWriter`

- fgpyo/util/metric.py
- fgpyo/util/tests/test_metric.py
Closes #88.
I've adapted the `DataclassWriter` from https://github.com/msto/dataclass_io/ to work with Metrics.
> feat: Add MetricWriter class

- fgpyo/sam/__init__.py
- fgpyo/sam/builder.py
- fgpyo/vcf/__init__.py
- pyproject.toml
- tests/fgpyo/sam/test_sam.py
- tests/fgpyo/util/test_inspect.py
This PR adds the mypy config introduced into our template in https://github.com/fulcrumgenomics/python-template/pull/28.
Error codes are now required on any `type: ignore` pragmas. This PR also adds error codes to any existing `ignore`s without a code.
> chore: Require error codes on `type: ignore` pragmas

- fgpyo/io/__init__.py
- fgpyo/util/metric.py
- tests/fgpyo/util/test_metric.py
Closes #88 
Closes #90 
This PR introduces a `MetricWriter` class. 
This PR is motivated by a limitation in `Metric.write()`, which does not permit appending metric instances to a file. The new class supports appending and streamed writing of metrics, validating that the existing file's structure matches the metrics being written. `MetricWriter` also supports optionally reordering or removing fields when writing.
- Added the `MetricWriter` class, which supports context-managed appending and writing of Metrics to file.
- Added `Metric.keys()`, `Metric.items()`, and `Metric.formatted_items()`. These are companions to the existing `Metric.values()` and `Metric.formatted_values()`, and provide analogous key/item views
- Added `Metric._read_header` and the associated `MetricFileHeader` class, …
> feat: MetricWriter

- fgpyo/sam/__init__.py
- tests/fgpyo/sam/test_cigar.py
- add cigar utility method get_alignment_offsets to find the offsets of the aligned segment in the read
- tests included
> feat: add cigar utility method get_alignment_offsets 

- pyproject.toml
Otherwise `mypy` fails locally.
> chore: exclude `site/` and `docs/` from mypy checks

- fgpyo/sam/__init__.py
- tests/fgpyo/sam/test_template_iterator.py
Having a view into the R1 alignments or R2 alignments without having to manually chain the iterables each time would be helpful for dealing with complex alignment scenarios. Would these two methods be a welcome addition?
> Add all_r1 and all_r2 methods on Template

- fgpyo/sam/__init__.py
- tests/fgpyo/sam/test_template_iterator.py
Currently, `Template` treats "secondary supplemental" alignments as both secondary alignments and as supplemental alignments. Before this PR, `Template` would _**add**_ the "secondary supplemental" alignments into both the secondary and supplementary lists, thereby duplicating them. This behavior makes it difficult to use `Template` in complex alignment scenarios since there are duplicated records across both the secondary and supplementary lists e.g. records become duplicated when writing to a BAM file with `template.write_to(writer)`.
It would be more intuitive to me that supplemental alignments of a secondary alignment belong in the "supplementary" bin instead of both the secondary and the supplementary bin. With this PR, the fields of Template become more specific:
- Primary: all …
> Template to treat 'secondary supplemental' as supplemental

- fgpyo/sam/__init__.py
- tests/fgpyo/sam/test_sam.py
I have a project where I am re-building a complex alignment situation for a template and it involves an assessment of read pair orientation and whether the new pair is "proper" or not.
The functions in this PR allow for an optional R2 such as when you are iterating through a BAM in coordinate order and don't have easy access to the R2. When this happens, R1 is required to have enough mate information to derive the pair status and whether or not the read pair is "proper".
The implementation honors what is implemented in HTSJDK/fgbio but with:
1. Fewer exceptions by using `None` instead of an exception, when possible
2. Proper pair status also considers template length / insert size
> Add a function for determining read pair orientation

- fgpyo/util/logging.py
- tests/fgpyo/util/test_logging.py
Often I am iterating through a BAM by query name and find I'm having to manually loop over all records to increment the progress logger. This new method would make logging all the records in a template more convenient.
> Add a method for progress logging multiple alignments

- fgpyo/sam/__init__.py
- fgpyo/util/inspect.py
- tests/fgpyo/sam/test_sam.py
> fix: `sum_of_base_qualities()` returns zero when a record has no base qualities

- fgpyo/util/metric.py
- tests/fgpyo/util/test_metric.py
I stumbled upon the fact that `csv.DictWriter` uses windows  new line endings by default. This PR lets you change that when using `MetricWriter`.
I'm arguing for the default to be `"\n"` instead of `os.linesep` because:
- [Python has universal new line support](https://peps.python.org/pep-0278/) (so it doesn't care what we do)
- If you're working on a shared analysis and checking in files to version control, you don't want to worry about if you're running on the same OS as your collaborator
- In my experience, more bioinformatics tools have problems with windows line endings than with unix line endings
> feat: allow lineterminator specification in MetricWriter

- fgpyo/fasta/sequence_dictionary.py
- pyproject.toml
- tests/fgpyo/fasta/data/sequence.dict
- tests/fgpyo/fasta/test_sequence_dictionary.py
- in addition to pysam SAM headers and SAM header dicts, SeqDicts can now be initialized from SAM file paths and pysam SAM files
- added basic tests for this new functionality
> feat: overloaded 'SeqDict.from_sam()' method to support SAM files (#176)

- fgpyo/util/metric.py
- tests/fgpyo/util/test_metric.py
Fixes #216
Also, strips any flanking whitespace when formatting a float into a string.
> feat: trim flanking whitespace when reading a metric

- pyproject.toml
Following the release process here:
- https://github.com/fulcrumgenomics/fgpyo/blob/main/CONTRIBUTING.md#creating-a-release-on-pypi
This release includes the following commits:
- https://github.com/fulcrumgenomics/fgpyo/pull/220
- https://github.com/fulcrumgenomics/fgpyo/pull/183
- https://github.com/fulcrumgenomics/fgpyo/pull/223
- https://github.com/fulcrumgenomics/fgpyo/pull/217
- https://github.com/fulcrumgenomics/fgpyo/pull/226
- https://github.com/fulcrumgenomics/fgpyo/pull/227
- https://github.com/fulcrumgenomics/fgpyo/pull/204
> chore(release): bump to 1.1.0

- fgpyo/util/inspect.py
- fgpyo/util/types.py
- tests/fgpyo/util/test_types.py
> feat: support PEP604 syntax `str | None`

- .github/workflows/publish_fgpyo.yml
- .github/workflows/readthedocs.yml
- .github/workflows/tests.yml
- .github/workflows/wheels.yml
I believe the release process is broken because we've pinned to an older runner and packages are no longer available for that distribution. It should be OK to use `ubuntu-latest` and I generally recommend it.
See broken GitHub Action here:
- https://github.com/fulcrumgenomics/fgpyo/actions/runs/16527405530/job/46744264738
> Ensure we are using Ubuntu latest in GitHub CI

- fgpyo/sam/__init__.py
- tests/fgpyo/sam/test_cigar.py
Closes #169 
For the same reasons we concluded `__len__()` is a footgun for Cigar, we also should remove `__getitem__`. A more careful explanation of why is contained in the associated issue.
> Remove __getitem__ from Cigar

- CONTRIBUTING.md
- ci/check.sh
This PR updates `ci/check.sh` and `CONTRIBUTING.md` to reflect `uv` conventions I've seen in practice.
- Removed checks for virtual environments from `ci/check.sh`
- Simplified environment setup instructions
> chore: Update `ci/check.sh` and `CONTRIBUTING.md` to use primary `uv` interface

- fgpyo/__init__.py
- fgpyo/_requirements.py
- tests/fgpyo/test_requirements.py
Closes #132 
I've been using this implementation in a client repo and found it helpful, so thought it would be good to transfer it over.
I do still think the utility presents a possible footgun for coverage checks, since both the happy and unhappy paths share a single line of code, and we may want to consider including a warning in the documentation.
> feat: `require()`
